#!/bin/bash

yum install createrepo -y                                                                           # Make your repo dir

mkdir -p /repos/centos/7/extras/x86_64/Packages

cp helloworld-0.1-1.el7.centos.x86_64.rpm /repos/centos/7/extras/x86_64/Packages   # Replace 'helloworld*' with your package

createrepo /repos/centos/7/extras/x86_64/Packages
#secure copy packages to your home directory
scp rpmbuild/RPMS/x86_64/hello-0.1-1.el7.centos.x86_64.rpm yum-repo2:/home/fadliebra2012
#If get error or permisson deny download repos file on your
rpm server and upload it to your client or yum server.

#update your 'yum' server
createrepo --update /repos/centos/7/extras/x86_64/Packages/                        # Update after every change

 #install apache server

yum -y install httpd                                                              # Now install apache so you can serve your repo over the web

#enable and start apache server

systemctl enable && start httpd

setenforce 0

#check if apache server works (welcome webpage)
#edit this file
#vim /etc/httpd/conf.d/welcome.conf
#comment out all lines and save 
# restart your apache server


#Create a symbolic link
 #ln -s /var/www/html/CentOS /repos/centos/7/extras/x86_64/Packages

ln -s  /repos/centos /var/www/html/centos                                         # Link your repos in
cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak                      # Make a copy of our origonal httpd.conf

sed -i '144i     Options All' /etc/httpd/conf/httpd.conf                          # Configure apache
sed -i '145i    # Disable directory index so that it will index our repos' /etc/httpd/conf/httpd.conf
sed -i '146i     DirectoryIndex disabled' /etc/httpd/conf/httpd.conf

sed -i 's/^/#/' /etc/httpd/conf.d/welcome.conf                                    # Disables the defualt welcome page in the recommended way

chown -R apache:apache /repos/

systemctl restart httpd


# At this point you should be able to see your repository structure when you hit the website

# Last step is to configure your new yum repository on a client:


#Create a configuration file 
#cd /etc/yum.repos.d
#vim local.repo
#[mylocalrepo]
#name=My CentOS Repo
#baseurl=http://repos/centos/7/extras/x86_64/Packages
#gpgcheck=0
#enabled=1

systemctl enable && restart httpd


                                                 

                            


















