#!/bin/bash
        echo "This is Fadil's Gcloud Automation"
        echo "Authorizing fjemal01 for this project..."
        gcloud auth login Fadil.Jemal@seattlecolleges.edu --no-launch-browser
        echo "Enabling billing..."
        #gcloud alpha billing accounts projects link   nti-320 --account-id=00189B-E1F480-31B987
        gcloud alpha billing accounts projects link gcloud --account-id=013283-D06D10-B9064D

       #echo "Setting admin account-id..."
        gcloud config set account Fadil.Jemal@seattlecolleges.edu
        echo "Setting the project for Configuration..."
        #gcloud compute instances create projects/gcloud-170421
        gcloud compute instances create projects/gcloud-204001	
        gcloud config set project gcloud
        echo "Setting zone/region for Configuration..."
        gcloud config set compute/zone us-central1-a
        gcloud config set compute/region us-central1
        echo "Creating firewall-rules..."
        gcloud compute firewall-rules create allow-http --description "Incoming http allowed." \
            --allow tcp:80
        gcloud compute firewall-rules create allow-ldap --description "Incoming ldap allowed." \
            --allow tcp:636
        gcloud compute firewall-rules create allow-postgresql --description "Posgresql allowed." \
            --allow tcp:5432
            gcloud compute firewall-rules create allow-https --description "Incoming https allowed." \
            --allow tcp:443
        gcloud compute firewall-rules create allow-django --description "Django connection allowed." \
            --allow tcp:8000
        gcloud compute firewall-rules create allow-ftp --description "FTP Allowed." \
            --allow tcp:21
        echo "Creating the rsyslog server instance and running the install script..."
        gcloud compute instances create rsyslog \
            --image-family centos-7 \
            --image-project centos-cloud \
            --machine-type f1-micro \
            --scopes cloud-platform \
           --metadata-from-file startup-script=/tmp/NTI-310/automation_scripts/rsyslog-auto \
     echo "Creating the ldap server instance and running the install script..."
         gcloud compute instances create ldap-server \
         --image-family centos-7 \
         --image-project centos-cloud \
         --machine-type f1-micro \
         --scopes cloud-platform \
        --metadata-from-file startup-script=/tmp/NTI-310/automation_scripts/ldap-server-auto \
echo "creating the nfs server and running the install script..."
gcloud compute instances create nfs \
    --image-family centos-7 \
    --image-project centos-cloud \
    --machine-type f1-micro \
    --scopes cloud-platform \
    --metadata-from-file startup-script=/tmp/NTI-310/automation_scripts/nfs-server-auto \
    echo "Creating the postgres server and running the install script..."
gcloud compute instances create postgres \
    --image-family centos-7 \
    --image-project centos-cloud \
    --machine-type f1-micro \
    --scopes cloud-platform \
    --metadata-from-file startup-script=/tmp/NTI-310/automation_scripts/postgres-server \
echo "Creating the django server and running the install script..."
gcloud compute instances create django-a \
    --image-family centos-7 \
    --image-project centos-cloud \
    --machine-type f1-micro \
    --scopes cloud-platform \
    --metadata-from-file startup-script=/tmp/NTI-310/automation_scripts/django

    
