#!/bin/bash
#install git to clone your git repo
yum -y install git
git clone https://github.com/fjemal/nti-320.git /tmp/NTI-320
#Disable SELinux
sed -i "s/SELINUX=enforcing/SELINUX=permissive/" /etc/sysconfig/selinux
setenforce 0
#Modify /etc/selinux/config and change enforcing to disabled.
#Install Prerequisites
yum install httpd php php-cli gcc glibc glibc-common gd gd-devel net-snmp openssl-devel wget unzip -y
#https://www.unixmen.com/install-configure-nagios-4-centos-7/
#http://www.itzgeek.com/how-tos/linux/centos-how-tos/monitor-centos-7-rhel-7-using-nagios-4-0-7.html
#create a user and group for Nagios to use.
useradd nagios

groupadd nagcmd

usermod -a -G nagcmd nagios

usermod -a -G nagcmd apache 

#Download and Install Nagios and nagios-plugins
cd /tmp
wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.3.1.tar.gz
tar zxf nagios-4.3.1.tar.gz

wget http://www.nagios-plugins.org/download/nagios-plugins-2.2.0.tar.gz

tar zxf nagios-plugins-2.2.0.tar.gz

cd nagios-4.3.1

#Now that the files are extracted, let's start compiling Nagios!
./configure --with-command-group=nagcmd
make all

make install

make install-init

make install-config

make install-commandmode

make install-webconf

#Creating a password for nagiosadmin
htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin

#Install Nagios Plugins
cd /tmp/nagios-plugins-2.2.0

./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl

make all 

make install
mkdir /usr/local/nagios/etc/servers

cd /tmp
sleep 5
curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
sleep 5

cd /tmp/nrpe-3.2.1/

./configure --enable-command-args

make all

make install-groups-users
make install

make install-config

#Update Services File
echo >> /etc/services
echo '# Nagios services' >> /etc/services
echo 'nrpe    5666/tcp' >> /etc/services

make install-init
systemctl enable nrpe.service

firewall-cmd --zone=public --add-port=5666/tcp
firewall-cmd --zone=public --add-port=5666/tcp --permanent

#/usr/local/nagios/etc/nrpe.cfg
#allowed_hosts=127.0.0.1,10.128.0.0

sed -i '/^allowed_hosts=/s/$/,10.138.0.0\/24/' /usr/local/nagios/etc/nrpe.cfg
sed -i 's/^dont_blame_nrpe=.*/dont_blame_nrpe=1/g' /usr/local/nagios/etc/nrpe.cfg

systemctl start nrpe.service

#Test NRPE
/usr/local/nagios/libexec/check_nrpe -H 127.0.0.1
systemctl start nrpe.service
systemctl stop nrpe.service
systemctl restart nrpe.service
systemctl status nrpe.service



#open server directory for monitoring configurations

#Start Nagios
service httpd start 
service nagios start



